name: servers-express-basics

on:
  push:
    paths:
      - 'servers/express/basics/**'
  pull_request:
    paths:
      - 'servers/express/basics/**'
  schedule:
    # Every day at 1am
    - cron:  '0 1 * * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        node-version: [12.x, 14.x]
    env:
      CI: true
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: npm install
      working-directory: './servers/express/basics'
    - name: npm install tap
      run: npm install --save-dev tap
      working-directory: './servers/express/basics'
    - name: npm run test
      run: npm run test
      working-directory: './servers/express/basics'
